parser: Use a lookup table for Delimiter::from_byte.
servo/rust-cssparser pull request #358
Opened 2023-09-06 13:28 UTC by emilio

It's faster.

2023-09-06 13:28 UTC, emilio commented
r? @tiaanl

2023-09-10 08:24 UTC, tiaanl commented
@emilio Did you measure the performance of this change somewhere?

2023-09-10 12:24 UTC, emilio commented
@tiaanl Our similar `match_byte` optimization is a huge perf improvement in the tokenizer, see #128. So I didn't measure this function explicitly but I'd expect similar gains.

2023-09-10 15:50 UTC, emilio commented
Built a benchmark for this because I had some time. Before:

```
test tests::delimiter_from_byte ... bench:     177,361 ns/iter (+/- 7,390)
```

After:

```
test tests::delimiter_from_byte ... bench:      46,917 ns/iter (+/- 906)
```

2023-09-11 08:12 UTC, tiaanl requested changes
I was a bit skeptical about this one. It was either a few conditional jump instructions or a few memory accesses (the buffer doesn't fit fully into a cache line) and I was betting the memory accesses would take longer.

Benchmark numbers look like a good improvement.

2023-09-11 08:13 UTC, emilio commented on src/tests.rs
> +            for i in 0..255 {
Indeed.

2023-09-11 08:13 UTC, emilio commented on src/parser.rs
> +        const TABLE: [Delimiters; 255] = {
Whoops, thanks!

2023-09-11 08:26 UTC, emilio commented
Updated, thanks for the review @tiaanl!

2023-09-11 08:31 UTC, tiaanl approved these changes

2023-09-11 08:45 UTC, merged